sudo: false

language: python

python:
  - 3.5.2
  - 3.8.1

install: 
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
  - export FLASK_DEBUG=1

script:
  # unit tests
  - python -m pytest -v
