"""empty message

Revision ID: 1fd25c986993
Revises: 2b8bb5fd4ac4
Create Date: 2020-02-29 05:13:53.826890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd25c986993'
down_revision = '2b8bb5fd4ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foundation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    op.drop_table('status')
    op.drop_table('scope')
    op.drop_table('motivation')
    op.drop_table('foundation')
    op.drop_table('diag')
    op.drop_table('arq')
    # ### end Alembic commands ###
