"""empty message

Revision ID: 7283ffa51bc8
Revises: 7c29eae33d5e
Create Date: 2020-04-05 18:37:29.916522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7283ffa51bc8'
down_revision = '7c29eae33d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('teams', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisions')
    # ### end Alembic commands ###
