"""empty message

Revision ID: 7c29eae33d5e
Revises: a1c323672fd2
Create Date: 2020-04-05 18:18:46.319058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c29eae33d5e'
down_revision = 'a1c323672fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conclutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thanks')
    op.drop_table('recomendations')
    op.drop_table('conclutions')
    # ### end Alembic commands ###
