"""empty message

Revision ID: 8fadd5ee97b0
Revises: ea6e36460b08
Create Date: 2020-02-02 22:33:15.849227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fadd5ee97b0'
down_revision = 'ea6e36460b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('hola', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'hola')
    # ### end Alembic commands ###
