"""empty message

Revision ID: a1c323672fd2
Revises: e273c64b4b9e
Create Date: 2020-04-05 16:41:17.300939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c323672fd2'
down_revision = 'e273c64b4b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamLeaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('productO_id', sa.Integer(), nullable=True),
    sa.Column('scrumM_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documentation.id'], ),
    sa.ForeignKeyConstraint(['productO_id'], ['userA.id'], ),
    sa.ForeignKeyConstraint(['scrumM_id'], ['userA.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamLeaders')
    # ### end Alembic commands ###
